server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sharding_db
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true