spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/shop
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: admin123
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3316/shop
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: admin123