db:
  readonly:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3316/shop
    username: root
    password: admin123
  write:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: admin123