server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sharding_db
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        jdbc-url: jdbc:mysql://localhost:3316/ds0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: admin123
      ds1:
        jdbc-url: jdbc:mysql://localhost:3326/ds1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: admin123
    rules:
      sharding:
        default-database-strategy:
          standard:
            shardingColumn: u_id
            shardingAlgorithmName: database-inline
        default-table-strategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: orderinfo-inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
        #分片算法
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{u_id % 2}
          orderinfo-inline:
            type: INLINE
            props:
              algorithm-expression: order_info$->{id % 15}
        #表的策略
        tables:
          order_info:
            actual-data-nodes: ds$->{0..1}.order_info$->{0..15}
            column: id
            keyGeneratorName: snowflake
            table-strategy:
              standard:
                sharding-algorithm-name: orderinfo-inline
                sharding-column: id