spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3316/shop
        username: root
        password: admin123
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3326/shop
        username: root
        password: admin123
    rules:
      readwrite-splitting:
        data-sources:
          readwrite:
            type: Static
            props:
              write-data-source-name: ds0
              read-data-source-names: ds1